changes in library
internet-user-0/filmoteka-project-team pull request #4
Opened 2023-02-03 16:22 UTC by Valeriia2306

2023-02-03 20:08 UTC, internet-user-0 commented on src/components/library/library-header.html
> +    <a href="./" class="logo"
`href="https://internet-user-0.github.io/filmoteka-project-team/"` логотип з посиланням на сайт

2023-02-03 20:13 UTC, internet-user-0 commented on src/components/library/library-header.html
> +        <use href="./images/logo_sprite.svg#film_logo"></use></svg
`svg` вже є в гілці main в src можна видалити файли з svg і підєднати з основного

2023-02-03 22:30 UTC, internet-user-0 requested changes
добав розмітку в файл `library.html`

2023-02-04 13:27 UTC, Valeriia2306 commented
add changes

2023-02-04 13:30 UTC, internet-user-0 approved these changes
зараз зіллю

2023-02-04 13:30 UTC, merged